/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(tabs)'}/operario` | `/operario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(tabs)'}/admin` | `/admin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(tabs)'}/teleoperador` | `/teleoperador`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}${'/(tabs)'}/operario` | `/operario`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}${'/(tabs)'}/admin` | `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}${'/(tabs)'}/teleoperador` | `/teleoperador`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}${'/(tabs)'}/operario${`?${string}` | `#${string}` | ''}` | `/operario${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}${'/(tabs)'}/admin${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}${'/(tabs)'}/teleoperador${`?${string}` | `#${string}` | ''}` | `/teleoperador${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(tabs)'}/operario` | `/operario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(tabs)'}/admin` | `/admin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}${'/(tabs)'}/teleoperador` | `/teleoperador`; params?: Router.UnknownInputParams; };
    }
  }
}
